user:
  userName: 开发环境-刘亦菲
  sex: 女
  age: 18

server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_db?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: nb046
    driver-class-name: com.mysql.cj.jdbc.Driver
