# application.yaml (默认配置文件)
user:
  userName: 刘亦菲
  sex: 女
  age: 20

server:
  port: 8080  # 端口配置

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_db?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: nb046
    driver-class-name: com.mysql.cj.jdbc.Driver
  mybatis:
    mapper-locations: classpath*:/mapper/**/*.xml
    type-aliases-package: com.example.demo.entity
  #  profiles:
  #    active: dev  # 注意这里不需要等号和冒号
