# application.yaml (默认配置文件)
user:
  userName: nick
  sex: 女
  age: 20

server:
  port: 8080  # 端口配置
  servlet:
    context-path: /shang


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_db?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: nb046
    driver-class-name: com.mysql.cj.jdbc.Driver


logging:
  level:
    com.example.demo: debug